name: flutter_shared_codebase
description: Shared codebase to be used across different apps
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.8
  localstorage: ^3.0.2+5
  lzstring: ^1.0.2+1
  url_launcher: ^5.4.5
  outline_material_icons: ^0.1.1
  package_info: ^0.4.0+17

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
