name: flutter_shared_codebase
description: Shared codebase to be used across different apps
version: 0.0.3
author:
homepage:

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.12+2
  localstorage: ^3.0.3+6
  lzstring: ^1.0.2+1
  url_launcher: ^5.7.8
  outline_material_icons: ^0.1.1
  package_info: ^0.4.3
  connectivity: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
